### ISSUE TITLE
Nothing shows up

### ISSUE THREAD

**Issue by abejfehr** [zenorocha/jquery-github#46]
I have no idea why, but my Github repos disappeared off my website even though I didn't change any code related to displaying them. I troubleshooted for a little while and after nearly giving up I then decided for some reason to come here and see if it was a global issue, and it somehow turns out, it is.

Visiting your page shows this in my browser(s): 
![screen shot 2015-12-06 at 10 35 54 pm](https://cloud.githubusercontent.com/assets/3917428/11618526/0a59735e-9c6a-11e5-8552-100544daf7e5.png)

Interestingly enough, no 404's were given in the Developer Tools.

This made me realize: this service heavily relies on something else (github), and when that's not working it doesn't display anything. For a fallback, would it be possible to display dumb links to repositories instead?

**Comment by zenorocha** [comment]
You should run bower install first, which will fetch jQuery.
